name: ANOLE
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - accelerate==0.31.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==24.2.0
      - bidict==0.23.1
      - blessed==1.20.0
      - blinker==1.8.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - config==0.5.1
      - datasets==3.1.0
      - datetime==5.5
      - deepspeed==0.14.4
      - dill==0.3.8
      - distro==1.9.0
      - evaluate==0.4.3
      - filelock==3.16.1
      - flask==3.0.3
      - flask-socketio==5.4.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gpustat==1.1.1
      - gputil==1.4.0
      - graphviz==0.20.3
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonlines==4.0.0
      - markupsafe==3.0.2
      - mpi4py-mpich==3.1.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.64.0
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.0.1
      - pip==25.0.1
      - propcache==0.2.1
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-engineio==4.10.1
      - python-socketio==5.11.4
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - simple-websocket==1.1.0
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - torch==2.1.1
      - torchviz==0.0.2
      - tqdm==4.66.5
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - wsproto==1.2.0
      - xformers==0.0.23
      - xxhash==3.5.0
      - yarl==1.18.3
      - zope-interface==7.1.1

